config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see:
  # https://guides.rubyonrails.org/routing.html

  root 'shortcut_urls#new'

  get '/404', to: 'errors#not_found'

  post 'create-url', to: 'shortcut_urls#create', as: :create_shortcut
  get '/:token', to: 'shortcut_urls#show', as: :show_shortcut
end

app/models/application_record.rb
# frozen_string_literal: true

# Base Application record class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortcut_url.rb
# frozen_string_literal: true

# Model to represent Shortcut URL
class ShortcutUrl < ApplicationRecord
  validates :redirect_to, presence: true
  validates :token, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

# Controller to handle requests to create short URL
class ErrorsController < ApplicationController
  def not_found
    render :not_found, status: 404
  end
end

app/controllers/shortcut_urls_controller.rb
# frozen_string_literal: true

# Controller to handle requests to create short URL
class ShortcutUrlsController < ApplicationController
  def new
    @shortcut_url ||= ShortcutUrl.new
  end

  def create
    @shortcut_url = CreateShortcutUrlService.perform(*new_shortcut_url_params)

    if @shortcut_url.persisted?
      render :create
    else
      render :new
    end
  end

  def show
    redirect_to(VisitShortcutUrlService.perform(params[:token]))
  end

  private

  def new_shortcut_url_params
    params.require(:shortcut_url).permit(:redirect_to)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Module to store shared helper methods
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortifier</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col col-sm-6 col-md-6 col-lg-6 col-xl-6 text-center">
          <%= image_tag(
                  'https://www.selina.com/static/media/selina_logo_black.b62a0982.svg',
                  alt: 'Selina',
                  class: 'rounded mx-auto d-block selina-logo'
              ) %>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shortcut_urls/create.html.erb
<h1>Your short URL:</h1>

<%= link_to(
        show_shortcut_url(@shortcut_url.token),
        show_shortcut_url(@shortcut_url.token),
        class: 'btn btn-link short-url-link',
        target: '_blank'
    ) %>

<div>
  <%= link_to(root_url, class: 'btn btn-primary btn-lg') do %>
    <span class="glyphicon glyphicon-home"></span> Create another
  <% end %>
</div>

app/views/shortcut_urls/new.html.erb
<%= form_for(@shortcut_url, url: create_shortcut_url) do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <ul class="shortcut-errors">
        <% form.object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.url_field(
            :redirect_to,
            required: true,
            class: 'form-control form-control-lg form-control-rounded',
            placeholder: 'Enter original URL'
        ) %>
  </div>

  <div class="form-group text-center">
    <%= form.button('Get short URL', class: 'btn btn-primary btn-lg') %>
  </div>
<% end %>